version: '3.8'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  prompt-optimizer:
    build: .
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=your-api-key
    depends_on:
      - redis
